In [4]:
!pip install transformers #transfromers 설치

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 5.5 MB 31.2 MB/s 
     |████████████████████████████████| 163 kB 71.4 MB/s 
     |████████████████████████████████| 7.6 MB 59.3 MB/s 


마스크드 언어모델과 토크나이져

In [5]:
from transformers import TFBertForMaskedLM, AutoTokenizer #TFBertForMaskedLM 과 AutoTokenizer 모듈을 불러온다

In [6]:
model = TFBertForMaskedLM.from_pretrained('bert-large-uncased') # 모델생성
tokenizer = AutoTokenizer.from_pretrained('bert-large-uncased') # 토큰나이져 생성

Downloading:   0%|          | 0.00/571 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.47G [00:00<?, ?B/s]

All model checkpoint layers were used when initializing TFBertForMaskedLM.

All the layers of TFBertForMaskedLM were initialized from the model checkpoint at bert-large-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForMaskedLM for predictions without further training.


Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Bert 입력

In [12]:
#인코딩
inputs = tokenizer('Soccer is a really fun [MASK].', return_tensors='tf')

In [13]:
#인코딩 결과 확인하기
print(inputs['input_ids'])

tf.Tensor([[ 101 4715 2003 1037 2428 4569  103 1012  102]], shape=(1, 9), dtype=int32)


In [14]:
#세그먼트 인코딩 
print(inputs['token_type_ids'])

tf.Tensor([[0 0 0 0 0 0 0 0 0]], shape=(1, 9), dtype=int32)


In [15]:
#어텐션 마스크 확인하기
print(inputs['attention_mask'])

tf.Tensor([[1 1 1 1 1 1 1 1 1]], shape=(1, 9), dtype=int32)


[MASK] 토큰 예측하기 FillMaskPipeline 활용한

In [17]:
from transformers import FillMaskPipeline
pip = FillMaskPipeline(model=model, tokenizer=tokenizer)

In [18]:
pip('Soccer is a really fun [MASK].')

[{'score': 0.7621114253997803,
  'token': 4368,
  'token_str': 'sport',
  'sequence': 'soccer is a really fun sport.'},
 {'score': 0.2034202218055725,
  'token': 2208,
  'token_str': 'game',
  'sequence': 'soccer is a really fun game.'},
 {'score': 0.012208531610667706,
  'token': 2518,
  'token_str': 'thing',
  'sequence': 'soccer is a really fun thing.'},
 {'score': 0.0018630304839462042,
  'token': 4023,
  'token_str': 'activity',
  'sequence': 'soccer is a really fun activity.'},
 {'score': 0.0013354880502447486,
  'token': 2492,
  'token_str': 'field',
  'sequence': 'soccer is a really fun field.'}]

In [20]:
pip('The Avengers is a really fun [MASK].')

[{'score': 0.256289541721344,
  'token': 2265,
  'token_str': 'show',
  'sequence': 'the avengers is a really fun show.'},
 {'score': 0.17284110188484192,
  'token': 3185,
  'token_str': 'movie',
  'sequence': 'the avengers is a really fun movie.'},
 {'score': 0.11107730120420456,
  'token': 2466,
  'token_str': 'story',
  'sequence': 'the avengers is a really fun story.'},
 {'score': 0.07248970866203308,
  'token': 2186,
  'token_str': 'series',
  'sequence': 'the avengers is a really fun series.'},
 {'score': 0.07046632468700409,
  'token': 2143,
  'token_str': 'film',
  'sequence': 'the avengers is a really fun film.'}]

In [21]:
pip('I want to [MASK] this moring.')

[{'score': 0.16576340794563293,
  'token': 2644,
  'token_str': 'stop',
  'sequence': 'i want to stop this moring.'},
 {'score': 0.16509464383125305,
  'token': 3102,
  'token_str': 'kill',
  'sequence': 'i want to kill this moring.'},
 {'score': 0.05930911377072334,
  'token': 2156,
  'token_str': 'see',
  'sequence': 'i want to see this moring.'},
 {'score': 0.038061972707509995,
  'token': 2079,
  'token_str': 'do',
  'sequence': 'i want to do this moring.'},
 {'score': 0.024515291675925255,
  'token': 6033,
  'token_str': 'destroy',
  'sequence': 'i want to destroy this moring.'}]

In [22]:
pip('Hello my [MASK].')

[{'score': 0.14902271330356598,
  'token': 2293,
  'token_str': 'love',
  'sequence': 'hello my love.'},
 {'score': 0.1362188309431076,
  'token': 2767,
  'token_str': 'friend',
  'sequence': 'hello my friend.'},
 {'score': 0.10659206658601761,
  'token': 6203,
  'token_str': 'dear',
  'sequence': 'hello my dear.'},
 {'score': 0.0553574375808239,
  'token': 2814,
  'token_str': 'friends',
  'sequence': 'hello my friends.'},
 {'score': 0.04324954375624657,
  'token': 9548,
  'token_str': 'darling',
  'sequence': 'hello my darling.'}]

In [23]:
pip('If we can’t accept [MASK], then we’re no [MASK] than the bad guys.')

[[{'score': 0.34302598237991333,
   'token': 2008,
   'token_str': 'that',
   'sequence': '[CLS] if we can ’ t accept that, then we ’ re no [MASK] than the bad guys. [SEP]'},
  {'score': 0.24821707606315613,
   'token': 2009,
   'token_str': 'it',
   'sequence': '[CLS] if we can ’ t accept it, then we ’ re no [MASK] than the bad guys. [SEP]'},
  {'score': 0.13592810928821564,
   'token': 2068,
   'token_str': 'them',
   'sequence': '[CLS] if we can ’ t accept them, then we ’ re no [MASK] than the bad guys. [SEP]'},
  {'score': 0.08710098266601562,
   'token': 2023,
   'token_str': 'this',
   'sequence': '[CLS] if we can ’ t accept this, then we ’ re no [MASK] than the bad guys. [SEP]'},
  {'score': 0.012525465339422226,
   'token': 2477,
   'token_str': 'things',
   'sequence': '[CLS] if we can ’ t accept things, then we ’ re no [MASK] than the bad guys. [SEP]'}],
 [{'score': 0.9655157923698425,
   'token': 2488,
   'token_str': 'better',
   'sequence': '[CLS] if we can ’ t accept [MAS

In [25]:
pip('With great [MASK] comes great [MASK].')

[[{'score': 0.04243915528059006,
   'token': 2373,
   'token_str': 'power',
   'sequence': '[CLS] with great power comes great [MASK]. [SEP]'},
  {'score': 0.041598547250032425,
   'token': 3112,
   'token_str': 'success',
   'sequence': '[CLS] with great success comes great [MASK]. [SEP]'},
  {'score': 0.03689756244421005,
   'token': 3997,
   'token_str': 'strength',
   'sequence': '[CLS] with great strength comes great [MASK]. [SEP]'},
  {'score': 0.03057747334241867,
   'token': 7177,
   'token_str': 'wealth',
   'sequence': '[CLS] with great wealth comes great [MASK]. [SEP]'},
  {'score': 0.02822818234562874,
   'token': 2791,
   'token_str': '##ness',
   'sequence': '[CLS] with greatness comes great [MASK]. [SEP]'}],
 [{'score': 0.07403552532196045,
   'token': 5368,
   'token_str': 'responsibility',
   'sequence': '[CLS] with great [MASK] comes great responsibility. [SEP]'},
  {'score': 0.035846542567014694,
   'token': 3112,
   'token_str': 'success',
   'sequence': '[CLS] with